In [1]:
1+1

2

In [2]:
import numpy as np

In [5]:
list=[1,2,3,4]
arr=np.array(list)

In [6]:
arr

array([1, 2, 3, 4])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(4,)

In [11]:
arr1=np.array([[1,2,3],[4,5,6]])

In [13]:
# 2 Dimension array
arr1.shape

(2, 3)

In [14]:
arr1.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
arr1.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [16]:
arr1.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [17]:
arr1.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [18]:
np.array((1,2,3,4))

array([1, 2, 3, 4])

In [19]:
np.array({'a':1,'b':2})

array({'a': 1, 'b': 2}, dtype=object)

In [21]:
arr1.dtype

dtype('int64')

In [24]:
np.arange(1,10,2).reshape(5,1).shape

(5, 1)

In [28]:
np.arange(1,20,2).reshape(2,5).shape

(2, 5)

In [32]:
np.array(range(1,20,2))

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [33]:
np.arange(50,1,-2)

array([50, 48, 46, 44, 42, 40, 38, 36, 34, 32, 30, 28, 26, 24, 22, 20, 18,
       16, 14, 12, 10,  8,  6,  4,  2])

In [40]:
arr2=np.array([[[[1,2,3],[4,5,6],[7,8,9],[10,11,12],[13,14,15]]]])

In [41]:
type(arr2)

numpy.ndarray

In [42]:
arr2

array([[[[ 1,  2,  3],
         [ 4,  5,  6],
         [ 7,  8,  9],
         [10, 11, 12],
         [13, 14, 15]]]])

In [44]:
np.linspace(1,20,40).reshape(20,2)

array([[ 1.        ,  1.48717949],
       [ 1.97435897,  2.46153846],
       [ 2.94871795,  3.43589744],
       [ 3.92307692,  4.41025641],
       [ 4.8974359 ,  5.38461538],
       [ 5.87179487,  6.35897436],
       [ 6.84615385,  7.33333333],
       [ 7.82051282,  8.30769231],
       [ 8.79487179,  9.28205128],
       [ 9.76923077, 10.25641026],
       [10.74358974, 11.23076923],
       [11.71794872, 12.20512821],
       [12.69230769, 13.17948718],
       [13.66666667, 14.15384615],
       [14.64102564, 15.12820513],
       [15.61538462, 16.1025641 ],
       [16.58974359, 17.07692308],
       [17.56410256, 18.05128205],
       [18.53846154, 19.02564103],
       [19.51282051, 20.        ]])

In [46]:
np.zeros(10).reshape(5,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [47]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [48]:
np.ones((10,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [55]:
np.ones((5,3,6))

array([[[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]]])

In [57]:
5+np.ones((3,5))

array([[6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.],
       [6., 6., 6., 6., 6.]])

In [58]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [59]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [60]:
np.identity(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [62]:
print("Random number generation (Uniform Distribution)")
np.random.rand(5,5)

Random number generation (Uniform Distribution)


array([[0.11159988, 0.58606644, 0.78175873, 0.78585784, 0.30606156],
       [0.8236229 , 0.59978917, 0.74367784, 0.99502099, 0.99506821],
       [0.65067219, 0.44080889, 0.34981902, 0.34171587, 0.63961426],
       [0.04068865, 0.66948754, 0.49532438, 0.02139293, 0.55085785],
       [0.71845468, 0.28741715, 0.17840989, 0.78670735, 0.15494543]])

In [64]:
print("Random number following a normal distribution with mean =0 and std=1")
np.random.randn(5,4)

Random number following a normal distribution with mean =0 and std=1


array([[ 0.84228119,  0.42969329, -2.08847647,  0.66881721],
       [ 0.48869133, -0.35386764,  0.27880054,  0.01590046],
       [ 0.95763968,  1.16834844, -0.69968884, -0.95691824],
       [-0.26520599,  0.83719114, -0.8256954 , -1.13308061],
       [-2.46602748, -0.3913845 , -0.0394489 ,  1.59612323]])

In [73]:
np.random.randint(1,100,(4,5))

array([[47, 62, 52, 37, 47],
       [29, 88, 90, 66, 46],
       [34, 73, 46, 67, 92],
       [21, 82, 30, 94, 42]], dtype=int32)

In [75]:
arr=np.arange(0,11)

In [76]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [79]:
arr[2:7]

array([2, 3, 4, 5, 6])

In [80]:
arr[-1]

np.int64(10)

In [81]:
arr[-1:3:-1]

array([10,  9,  8,  7,  6,  5,  4])

In [82]:
arr1=np.random.randint(2,100,20).reshape(5,4)

In [83]:
arr1

array([[71, 77, 23, 63],
       [76, 66,  4, 44],
       [72, 69, 34, 48],
       [46,  9, 99, 63],
       [85,  8, 94, 86]], dtype=int32)

In [87]:
arr1[3:,1:]

array([[ 9, 99, 63],
       [ 8, 94, 86]], dtype=int32)

In [89]:
arr1[2:4,1:3]

array([[69, 34],
       [ 9, 99]], dtype=int32)

In [90]:
arr1

array([[71, 77, 23, 63],
       [76, 66,  4, 44],
       [72, 69, 34, 48],
       [46,  9, 99, 63],
       [85,  8, 94, 86]], dtype=int32)

In [96]:
arr1[2:4,0:4:3]

array([[72, 48],
       [46, 63]], dtype=int32)

In [97]:
# Universal Function

In [104]:
arr3=np.random.randint(1,100,(3,3))
arr2=np.random.randint(20,100,(3,3))

In [105]:
arr3

array([[95, 80, 92],
       [99, 42, 45],
       [ 3, 43, 22]], dtype=int32)

In [106]:
arr2

array([[27, 62, 54],
       [81, 82, 76],
       [54, 41, 29]], dtype=int32)

In [107]:
arr2*arr3

array([[2565, 4960, 4968],
       [8019, 3444, 3420],
       [ 162, 1763,  638]], dtype=int32)

In [108]:
arr2+arr3

array([[122, 142, 146],
       [180, 124, 121],
       [ 57,  84,  51]], dtype=int32)

In [109]:
arr2-arr3

array([[-68, -18, -38],
       [-18,  40,  31],
       [ 51,  -2,   7]], dtype=int32)

In [110]:
arr2/arr3

array([[ 0.28421053,  0.775     ,  0.58695652],
       [ 0.81818182,  1.95238095,  1.68888889],
       [18.        ,  0.95348837,  1.31818182]])

In [111]:
np.sqrt(arr2)

array([[5.19615242, 7.87400787, 7.34846923],
       [9.        , 9.05538514, 8.71779789],
       [7.34846923, 6.40312424, 5.38516481]])

In [112]:
np.exp(arr2)

array([[5.32048241e+11, 8.43835667e+26, 2.83075330e+23],
       [1.50609731e+35, 4.09399696e+35, 1.01480039e+33],
       [2.83075330e+23, 6.39843494e+17, 3.93133430e+12]])

In [114]:
np.log10(arr2)

array([[1.43136376, 1.79239169, 1.73239376],
       [1.90848502, 1.91381385, 1.88081359],
       [1.73239376, 1.61278386, 1.462398  ]])

In [115]:
arr1=np.arange(1,10)

In [116]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [119]:
# Broadcasting
arr1[2:]=1000

In [118]:
arr1

array([   1,    2, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [120]:
np.dot(arr2,arr3)

array([[ 8865,  7086,  6462],
       [16041, 13192, 12814],
       [ 9276,  7289,  7451]], dtype=int32)

In [121]:
np.matmul(arr2,arr3)

array([[ 8865,  7086,  6462],
       [16041, 13192, 12814],
       [ 9276,  7289,  7451]], dtype=int32)